import asyncio
import functools
import hashlib
from pathlib import Path

import discord
import numpy as np
import soundfile as sf

from logger_config import bot_logger

from . import settings


async def disconnect_voice(state):
    if state.voice_client:
        await state.voice_client.disconnect()
        state.voice_client = None
    if state.disconnect_task:
        if not state.disconnect_task.done():
            state.disconnect_task.cancel()
        state.disconnect_task = None


async def empty_channel_timeout(state):
    await asyncio.sleep(settings.EMPTY_CHANNEL_TIMEOUT_SECONDS)
    if state.voice_client and state.voice_client.is_connected():
        bot_logger.info(
            f"Bot left alone for {settings.EMPTY_CHANNEL_TIMEOUT_SECONDS} seconds in "
            f"'{state.voice_client.channel.name}'. Disconnecting."
        )
        await disconnect_voice(state)


async def ensure_voice_connected(ctx, state):
    if state.voice_client is None or not state.voice_client.is_connected():
        state.voice_client = await ctx.author.voice.channel.connect()
    return state.voice_client


async def play_file(ctx, state, filepath, sleep_interval=1):
    voice_client = await ensure_voice_connected(ctx, state)
    source = await discord.FFmpegOpusAudio.from_probe(str(filepath))
    voice_client.play(source)

    while voice_client.is_playing():
        await asyncio.sleep(sleep_interval)


async def audio_worker(state):
    while True:
        ctx, text = await state.request_queue.get()

        text_hash = hashlib.sha256(text.encode()).hexdigest()
        output_filename = settings.CACHE_DIR / f"{text_hash}.wav"

        if output_filename.exists():
            bot_logger.info(f"Playing from cache: {output_filename}")
        else:
            loop = asyncio.get_event_loop()
            try:
                await loop.run_in_executor(
                    None, functools.partial(fetch_and_cache_audio, text, output_filename, state)
                )
            except Exception as exc:
                await ctx.send(f"An error occurred while generating audio: {exc}")
                continue

        try:
            await ensure_voice_connected(ctx, state)
            state.last_tts_file = str(output_filename)
            source = await discord.FFmpegOpusAudio.from_probe(str(output_filename))
            state.voice_client.play(source)

            while state.voice_client.is_playing():
                await asyncio.sleep(1)

            await ctx.send(f"Played: '{text}'")
        except Exception as exc:
            await ctx.send(f"An error occurred: {exc}")


def fetch_and_cache_audio(text, output_filename: Path, state):
    bot_logger.info(f"Generating audio for: {text}")

    if state.pipeline is None:
        raise Exception("Kokoro pipeline not initialized")

    try:
        generator = state.pipeline(text, voice=settings.TTS_VOICE, speed=settings.TTS_SPEED)
        audio_segments = []
        for _, _, audio in generator:
            audio_segments.append(audio)

        if audio_segments:
            final_audio = np.concatenate(audio_segments)
            sf.write(str(output_filename), final_audio, settings.TTS_SAMPLE_RATE)
        else:
            bot_logger.warning(f"No audio generated for text: {text}")
            raise Exception("No audio generated by Kokoro")
    except Exception as exc:
        bot_logger.error(f"Error generating audio: {exc}")
        raise
